<div class="ez_mainL">
  <ul>
    <li>
      <a href="javascript:void(0)">物流基础信息</a>
      <ul class="tlevel">
        <li>
          <a href="javascript:void(0)" class="contentUrl" url="/Control/DestControl.aspx">目的地信息</a>
        </li>
        <li>
          <a href="basisinfo_wsj-物流基础信息 - 司机信息.html" >司机信息</a>
        </li>
        <li>
          <a href="basisinfo_wclxx-物流基础信息 - 车辆信息.html">车辆信息</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)">同城基础信息</a>
      <ul class="tlevel none">
        <li>
          <a href="basisinfo_tddxx-同城基础信息 - 段道信息.html" >段道信息</a>
        </li>
        <li>
          <a href="basisinfo_tpsxx-同城基础信息 - 配送信息.html" >配送员信息</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)">第三方快递基础信息</a>
      <ul class="tlevel none">
        <li>
          <a href="basisinfo_ddsf-第三方快递基础.html" >快递公司</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="othermail-其他邮件.html">其它邮件</a>
    </li>
    <li>
      <a href="javascript:void(0)">物流信息</a>
      <ul class="tlevel none">
        <li>
          <a href="logistics_wlist-物流-汇总列表.html">物流出库汇总列表</a>
        </li>
        <li>
          <a href="logistics_wdfh-物流-待发货.html">待发货</a>
        </li>
        <li>
          <a href="logistics_wyfh-物流-已发货.html">已发货</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)">同城</a>
      <ul class="tlevel none">
        <li>
          <a href="city_Tlist-同城-汇总列表.html">同城出库汇总表</a>
        </li>
        <li>
          <a href="city_Tdck-同城-待出库.html">待发货</a>
        </li>
        <li>
          <a href="city_Tdck-同城-已出库.html">已发货</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="javascript:void(0)">第三方快递</a>
      <ul class="tlevel none">
        <li>
          <a href="three_Slist-第三方-汇总列表.html">第三方出库汇总列表</a>
        </li>
        <li>
          <a href="three_Sdfh-第三方-待发货.html">待发货</a>
        </li>
        <li>
          <a href="three_Syfh-第三方-已发货.html">已发货</a>
        </li>
      </ul>
    </li>
  </ul>
</div>